### PR TITLE
Update pubspec.yaml

### PR DESCRIPTION
**Pull request by kururu-abdo**
please update webview package to latest version to solve some issues

### CODE REVIEW

**Comment by ahoshaiyan** [comment]
@kururu-abdo  Could you please specify what is the issue you are trying to solve here and why the update fixes it

**Comment by kururu-abdo** [comment]
> @kururu-abdo Could you please specify what is the issue you are trying to solve here and why the update fixes it

well.  i almost forgot:)
but i think when i install the package from pub.dev  i received this error:

Error: Couldn't find constructor 'WebViewController'.
final controller = WebViewController()

Error: Couldn't find constructor 'NavigationDelegate'.
..setNavigationDelegate(NavigationDelegate(onPageFinished: (pageUrl) {
^^^^^^^^^^^^^^^^^^


i installed the source code and update flutter . it worked well

**Comment by kururu-abdo** [comment]
i also tried to update webview plugin . i thought it was the source of problem

**Comment by Fghurayri** [comment]
Thank you @kururu-abdo. We just released a new version (`v2.0.3`) to support latest upgrades in the Flutter tooling and dependencies.

**Pull request closed without merging**
